### ISSUE TITLE
请问在 Future Preference Extractor 中用的未来时间，是用了标签中的真实时间吗？

### ISSUE THREAD

**Issue by Wonderdch** [wuziqi2/CFPRec#3]
因为我看代码中，[short_term_after_time](https://github.com/wuziqi2/CFPRec/blob/5946a66ac0d53fa03c33fe5bb2fe566525d1cfad/CFPRec.py#L317) 拿到了 target 之后的几次签到的真实时间。

PS：谢谢分享代码！

**Comment by wuziqi2** [comment]
不好意思之前正好有些忙忘记回复。是的，这个模型是given next one/multiple timestamp, 对应着推荐一个/多个 POI

**Comment by tt2615** [comment]
不好意思之前正好有些忙忘记回复。是的，这个模型是given next one/multiple timestamp, 对应着推荐一个/多个 POI

**Comment by Wonderdch** [comment]
> 不好意思之前正好有些忙忘记回复。是的，这个模型是given next one/multiple timestamp, 对应着推荐一个/多个 POI

多谢回复，我后面仔细看了代码也明白了，用的是 target POI 之后的 一个/多个 POI 的签到时间。
一开始我担心用到了 target POI 的签到时间😅
